//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardware
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computers
    {
        public string DeviceIP { get; set; }
        public string Motherboard { get; set; }
        public string GPU { get; set; }
        public string CPU { get; set; }
        public string Monitor { get; set; }
        public int Id { get; set; }
    }
}
