//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardware
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configurations
    {
        public string DeviceIP { get; set; }
        public int Id { get; set; }
        public Nullable<int> CPUkey { get; set; }
        public Nullable<int> GPUkey { get; set; }
        public Nullable<int> MONITORkey { get; set; }
    
        public virtual CPUs CPUs { get; set; }
        public virtual GPUs GPUs { get; set; }
        public virtual Monitors Monitors { get; set; }
    }
}
