//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardware
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motherboards
    {
        public string Name { get; set; }
        public string Power { get; set; }
        public string Socket { get; set; }
        public int Price { get; set; }
        public int Id { get; set; }
    }
}
